local h = require("helpers")
local config = require("pi.config")

h.t("defaults are present", function()
  config.setup({})
  local c = config.get()
  h.eq(c.executable, "pi")
  h.eq(c.window.width, 0.85)
  h.eq(c.window.border, "rounded")
  h.eq(c.keys.send, "<CR>")
  h.eq(c.rpc_timeout, 30)
end)

h.t("user opts override defaults and deep-merge nested tables", function()
  config.setup({ executable = "pi-dev", window = { width = 0.9 } })
  local c = config.get()
  h.eq(c.executable, "pi-dev")
  h.eq(c.window.width, 0.9)
  h.eq(c.window.height, 0.85, "untouched nested key survives merge")
  h.eq(c.window.border, "rounded")
end)

h.t("contexts user table is preserved", function()
  config.setup({ contexts = { ["@file"] = function() return "x" end } })
  h.eq(type(config.get().contexts["@file"]), "function")
end)
