local h = require("helpers")
local edits = require("pi.edits")
local session = require("pi.session")
local root = vim.fn.getcwd()

h.t("reload reloads an open unmodified buffer after tool end", function()
  local f = root .. "/tests/tmp_edits_a.txt"
  local fh = assert(io.open(f, "w")); fh:write("v1\n"); fh:close()
  local buf = vim.fn.bufadd(f)
  vim.cmd("edit " .. vim.fn.fnameescape(f))
  fh = assert(io.open(f, "w")); fh:write("v2\n"); fh:close()
  session.reset({})
  session.record_tool({ toolCallId = "t1", toolName = "write", args = { file_path = f } })
  edits.reload_after({ type = "tool_execution_end", toolCallId = "t1" })
  h.wait(1000, function() return table.concat(vim.api.nvim_buf_get_lines(buf, 0, -1, false), "\n") == "v2" end,
    "buffer reloaded")
  os.remove(f)
end)

h.t("reload skips modified buffers", function()
  local f = root .. "/tests/tmp_edits_b.txt"
  local fh = assert(io.open(f, "w")); fh:write("v1\n"); fh:close()
  local buf = vim.fn.bufadd(f)
  vim.cmd("edit " .. vim.fn.fnameescape(f))
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "edited locally" })
  fh = assert(io.open(f, "w")); fh:write("v2\n"); fh:close()
  session.reset({})
  session.record_tool({ toolCallId = "t2", toolName = "write", args = { file_path = f } })
  edits.reload_after({ type = "tool_execution_end", toolCallId = "t2" })
  vim.wait(200)
  h.eq(table.concat(vim.api.nvim_buf_get_lines(buf, 0, -1, false), "\n"), "edited locally")
  os.remove(f)
end)

h.t("diff opens a scratch buffer with git output", function()
  local repo = root .. "/tests/tmp_git_repo"
  os.execute("rm -rf " .. repo)
  os.execute("mkdir -p " .. repo)
  os.execute("cd " .. repo .. " && git init -q && git config user.email t@t && git config user.name t")
  local fh = assert(io.open(repo .. "/a.txt", "w")); fh:write("one\n"); fh:close()
  os.execute("cd " .. repo .. " && git add a.txt && git commit -qm init")
  fh = assert(io.open(repo .. "/a.txt", "w")); fh:write("two\n"); fh:close()
  session.reset({})
  session.record_tool({ toolCallId = "t3", toolName = "edit", args = { file_path = repo .. "/a.txt" } })
  local buf = edits.diff()
  h.ok(buf and vim.api.nvim_buf_is_valid(buf), "diff buffer exists")
  local text = table.concat(vim.api.nvim_buf_get_lines(buf, 0, -1, false), "\n")
  h.ok(text:match("%-one") and text:match("%+two"), "diff hunks present: " .. text)
  os.execute("rm -rf " .. repo)
end)
