local h = require("helpers")
local session = require("pi.session")

h.t("transition covers the full table", function()
  h.eq(session.transition("idle", "agent_start", {}), "streaming")
  h.eq(session.transition("sending", "agent_start", {}), "streaming")
  h.eq(session.transition("streaming", "agent_end", { willRetry = true }), "sending")
  h.eq(session.transition("streaming", "agent_end", { willRetry = false }), "idle")
  h.eq(session.transition("idle", "compaction_start", {}), "compacting")
  h.eq(session.transition("compacting", "compaction_end", { willRetry = true }), "sending")
  h.eq(session.transition("compacting", "compaction_end", { success = true, willRetry = false }), "sending")
  h.eq(session.transition("compacting", "compaction_end", { success = false }), "idle")
  h.eq(session.transition("idle", "auto_retry_start", {}), "sending")
  h.eq(session.transition("sending", "auto_retry_end", { success = false }), "idle")
  h.eq(session.transition("streaming", "message_start", {}), "streaming")
end)

h.t("reset + get reflect state", function()
  session.reset({ model = { provider = "x", id = "y" }, thinkingLevel = "high",
    sessionId = "s1", sessionName = "n1", autoCompactionEnabled = true,
    isStreaming = false, isCompacting = false })
  local s = session.get()
  h.eq(s.status, "idle")
  h.eq(s.model.provider, "x")
  h.eq(s.thinking_level, "high")
  h.eq(s.session_name, "n1")
end)

h.t("apply_event drives status through a conversation", function()
  session.reset({})
  session.apply_event({ type = "agent_start" })
  h.eq(session.get().status, "streaming")
  session.apply_event({ type = "message_start", message = { role = "assistant", content = {} } })
  h.eq(session.get().current_message.role, "assistant")
  session.apply_event({ type = "agent_end", messages = { { role = "assistant" } }, willRetry = false })
  h.eq(session.get().status, "idle")
  h.eq(#session.get().messages, 1)
end)

h.t("record_tool extracts touched files", function()
  session.reset({})
  session.record_tool({ toolCallId = "t1", toolName = "write", args = { file_path = "a.txt" } })
  session.record_tool({ toolCallId = "t2", toolName = "edit", args = { file_path = "b.txt" } })
  session.record_tool({ toolCallId = "t3", toolName = "bash", args = {} })
  local t = session.touched_files()
  h.eq(#t, 2)
  h.eq(t[1], "a.txt")
  h.eq(t[2], "b.txt")
  session.end_tool("t1")
  h.ok(session.get().active_tools["t1"] == nil, "ended tool removed")
end)
