local h = require("helpers")
local ui = require("pi.ui")

h.t("geometry centers a large float and reserves input strip", function()
  local g = ui._geometry(200, 60, 0.85, 0.85)
  h.eq(g.width, 170)
  h.eq(g.height, 51)
  h.eq(g.input_h, 10)
  h.eq(g.chat_h, 40)
  h.eq(g.row, 4)
  h.eq(g.col, 15)
  h.eq(g.input_row, 4 + 40 + 1)
end)

h.t("toggle opens and closes windows", function()
  ui.toggle()
  h.ok(ui.is_open(), "open after toggle")
  h.ok(ui.chat_buf() ~= nil and ui.input_buf() ~= nil, "buffers exist")
  ui.toggle()
  h.ok(not ui.is_open(), "closed after second toggle")
end)

h.t("reopen preserves buffers", function()
  ui.toggle()
  local chat = ui.chat_buf()
  ui.toggle()
  ui.toggle()
  h.eq(ui.chat_buf(), chat, "same buffer object on reopen")
  ui.toggle()
end)
